name: Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: master
  # Run every day at midnight PST (0800 UTC)
  # https://crontab.guru/#0_8_*_*_*
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:24.3.3
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: ./rebar3 compile
        working-directory: /opt/erlang-lorawan
      - name: build test
        run: ./rebar3 as test compile
        working-directory: /opt/erlang-lorawan
      - name: tar
        run: tar -cvzf build.tar.gz -C _build/ .
        working-directory: /opt/erlang-lorawan
      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: /opt/erlang-lorawan/build.tar.gz
  xref:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: erlang:24.3.3
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}-xref
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: untar
        run: |
          mkdir _build
          tar -xvf build.tar.gz -C _build
      - name: xref
        run: ./rebar3 xref
  eunit:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: erlang:24.3.3
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}-eunit
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: untar
        run: |
          mkdir _build
          tar -xvf build.tar.gz -C _build
      - name: eunit
        run: ./rebar3 eunit -v
  dialyzer:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: erlang:24.3.3
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}-dialyzer
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: untar
        run: |
          mkdir _build
          tar -xvf build.tar.gz -C _build
      - name: dialyzer
        run: ./rebar3 dialyzer
  ct:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: erlang:24.3.3
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}-ct
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: untar
        run: |
          mkdir _build
          tar -xvf build.tar.gz -C _build
      - name: ct
        run: CT_LAGER=DEBUG ./rebar3 ct --readable=true
